export const US_STATE_CENTERS = {
    "alabama": { lat: 32.3182, lng: -86.9023, zoom: 6 },
    "alaska": { lat: 61.3707, lng: -152.4044, zoom: 3 },
    "arizona": { lat: 33.7298, lng: -111.4312, zoom: 3 },
    "arkansas": { lat: 34.9697, lng: -92.3731, zoom: 6 },
    "california": { lat: 36.1162, lng: -119.6816, zoom: 6 },
    "colorado": { lat: 39.0598, lng: -105.3111, zoom: 6 },
    "connecticut": { lat: 41.5978, lng: -72.7554, zoom: 8 },
    "delaware": { lat: 39.3185, lng: -75.5071, zoom: 8 },
    "florida": { lat: 27.7663, lng: -81.6868, zoom: 6 },
    "georgia": { lat: 33.0406, lng: -83.6431, zoom: 6 },
    "hawaii": { lat: 21.0943, lng: -157.4983, zoom: 8 },
    "idaho": { lat: 44.2405, lng: -114.4788, zoom: 6 },
    "illinois": { lat: 40.3495, lng: -88.9861, zoom: 6 },
    "indiana": { lat: 39.8494, lng: -86.2583, zoom: 6 },
    "iowa": { lat: 42.0115, lng: -93.2105, zoom: 6 },
    "kansas": { lat: 38.5266, lng: -96.7265, zoom: 6 },
    "kentucky": { lat: 37.6681, lng: -84.6701, zoom: 6 },
    "louisiana": { lat: 31.1695, lng: -91.8678, zoom: 6 },
    "maine": { lat: 44.6939, lng: -69.3819, zoom: 6 },
    "maryland": { lat: 39.0639, lng: -76.8021, zoom: 7 },
    "massachusetts": { lat: 42.2302, lng: -71.5301, zoom: 7 },
    "michigan": { lat: 43.3266, lng: -84.5361, zoom: 6 },
    "minnesota": { lat: 45.6945, lng: -93.9002, zoom: 6 },
    "mississippi": { lat: 32.7416, lng: -89.6787, zoom: 6 },
    "missouri": { lat: 38.4561, lng: -92.2884, zoom: 6 },
    "montana": { lat: 46.9219, lng: -110.4544, zoom: 5 },
    "nebraska": { lat: 41.1254, lng: -98.2681, zoom: 6 },
    "nevada": { lat: 38.3135, lng: -117.0554, zoom: 6 },
    "new hampshire": { lat: 43.4525, lng: -71.5639, zoom: 7 },
    "new jersey": { lat: 40.2989, lng: -74.5210, zoom: 7 },
    "new mexico": { lat: 34.8405, lng: -106.2485, zoom: 6 },
    "new york": { lat: 42.1657, lng: -74.9481, zoom: 6 },
    "north carolina": { lat: 35.6301, lng: -79.8064, zoom: 6 },
    "north dakota": { lat: 47.5289, lng: -99.7840, zoom: 6 },
    "ohio": { lat: 40.3888, lng: -82.7649, zoom: 6 },
    "oklahoma": { lat: 35.5653, lng: -96.9289, zoom: 6 },
    "oregon": { lat: 44.5720, lng: -122.0709, zoom: 6 },
    "pennsylvania": { lat: 40.5908, lng: -77.2098, zoom: 6 },
    "rhode island": { lat: 41.6809, lng: -71.5118, zoom: 8 },
    "south carolina": { lat: 33.8569, lng: -80.9450, zoom: 7 },
    "south dakota": { lat: 44.2998, lng: -99.4388, zoom: 6 },
    "tennessee": { lat: 35.7478, lng: -86.6923, zoom: 6 },
    "texas": { lat: 31.1060, lng: -97.6475, zoom: 5 },
    "utah": { lat: 40.1500, lng: -111.8624, zoom: 6 },
    "vermont": { lat: 44.0459, lng: -72.7107, zoom: 7 },
    "virginia": { lat: 37.7693, lng: -78.1700, zoom: 6 },
    "washington": { lat: 47.4009, lng: -121.4905, zoom: 6 },
    "west virginia": { lat: 38.4912, lng: -80.9545, zoom: 6 },
    "wisconsin": { lat: 44.2685, lng: -89.6165, zoom: 6 },
    "wyoming": { lat: 42.7475, lng: -107.2085, zoom: 6 }
};

export const highlightCountryList = [
    { id: "international", name: "International" },
    { id: "global", name: "Global" },
    { id: "Albania", name: "Albania" },
    { id: "Algeria", name: "Algeria" },
    { id: "Andorra", name: "Andorra" },
    { id: "Angola", name: "Angola" },
    { id: "Argentina", name: "Argentina" },
    { id: "Armenia", name: "Armenia" },
    { id: "Aruba", name: "Aruba" },
    { id: "Australia", name: "Australia" },
    { id: "Austria", name: "Austria" },
    { id: "Bahamas", name: "Bahamas" },
    { id: "Bahrain", name: "Bahrain" },
    { id: "Bangladesh", name: "Bangladesh" },
    { id: "Barbados", name: "Barbados" },
    { id: "Belgium", name: "Belgium" },
    { id: "Belize", name: "Belize" },
    { id: "Bhutan", name: "Bhutan" },
    { id: "Bolivia", name: "Bolivia" },
    { id: "Botswana", name: "Botswana" },
    { id: "Brazil", name: "Brazil" },
    { id: "Bulgaria", name: "Bulgaria" },
    { id: "Cambodia", name: "Cambodia" },
    { id: "Cameroon", name: "Cameroon" },
    { id: "Canada", name: "Canada" },
    { id: "Chile", name: "Chile" },
    { id: "China", name: "China" },
    { id: "Colombia", name: "Colombia" },
    { id: "Costa Rica", name: "Costa Rica" },
    { id: "Croatia", name: "Croatia" },
    { id: "Czechia", name: "Czechia" },
    { id: "Denmark", name: "Denmark" },
    { id: "Dominica", name: "Dominica" },
    { id: "Ecuador", name: "Ecuador" },
    { id: "Egypt", name: "Egypt" },
    { id: "El Salvador", name: "El Salvador" },
    { id: "Equatorial Guinea", name: "Equatorial Guinea" },
    { id: "Estonia", name: "Estonia" },
    { id: "Ethiopia", name: "Ethiopia" },
    { id: "Finland", name: "Finland" },
    { id: "France", name: "France" },
    { id: "Georgia", name: "Georgia" },
    { id: "Germany", name: "Germany" },
    { id: "Ghana", name: "Ghana" },
    { id: "Greece", name: "Greece" },
    { id: "Grenada", name: "Grenada" },
    { id: "Guam", name: "Guam" },
    { id: "Guatemala", name: "Guatemala" },
    { id: "Guinea", name: "Guinea" },
    { id: "Guyana", name: "Guyana" },
    { id: "Honduras", name: "Honduras" },
    { id: "Hong Kong", name: "Hong Kong" },
    { id: "Hungary", name: "Hungary" },
    { id: "Iceland", name: "Iceland" },
    { id: "India", name: "India" },
    { id: "Indonesia", name: "Indonesia" },
    { id: "Iran", name: "Iran" },
    { id: "Iraq", name: "Iraq" },
    { id: "Ireland", name: "Ireland" },
    { id: "Isle of Man", name: "Isle of Man" },
    { id: "Israel", name: "Israel" },
    { id: "Italy", name: "Italy" },
    { id: "Jamaica", name: "Jamaica" },
    { id: "Japan", name: "Japan" },
    { id: "Jersey", name: "Jersey" },
    { id: "Jordan", name: "Jordan" },
    { id: "Kazakhstan", name: "Kazakhstan" },
    { id: "Kenya", name: "Kenya" },
    { id: "Kosovo", name: "Kosovo" },
    { id: "Kuwait", name: "Kuwait" },
    { id: "Kyrgyzstan", name: "Kyrgyzstan" },
    { id: "Laos", name: "Laos" },
    { id: "Lebanon", name: "Lebanon" },
    { id: "Liberia", name: "Liberia" },
    { id: "Liechtenstein", name: "Liechtenstein" },
    { id: "Lithuania", name: "Lithuania" },
    { id: "Luxembourg", name: "Luxembourg" },
    { id: "Madagascar", name: "Madagascar" },
    { id: "Malawi", name: "Malawi" },
    { id: "Malaysia", name: "Malaysia" },
    { id: "Maldives", name: "Maldives" },
    { id: "Malta", name: "Malta" },
    { id: "Martinique", name: "Martinique" },
    { id: "Mauritius", name: "Mauritius" },
    { id: "Mexico", name: "Mexico" },
    { id: "Micronesia", name: "Micronesia" },
    { id: "Monaco", name: "Monaco" },
    { id: "Mongolia", name: "Mongolia" },
    { id: "Montenegro", name: "Montenegro" },
    { id: "Morocco", name: "Morocco" },
    { id: "Mozambique", name: "Mozambique" },
    { id: "Myanmar (Burma)", name: "Myanmar" },
    { id: "Namibia", name: "Namibia" },
    { id: "Nepal", name: "Nepal" },
    { id: "Netherlands", name: "Netherlands" },
    { id: "New Zealand", name: "New Zealand" },
    { id: "Nicaragua", name: "Nicaragua" },
    { id: "Nigeria", name: "Nigeria" },
    { id: "North Macedonia", name: "North Macedonia" },
    { id: "Northern Mariana Islands", name: "Northern Mariana Islands" },
    { id: "Norway", name: "Norway" },
    { id: "Oman", name: "Oman" },
    { id: "Pakistan", name: "Pakistan" },
    { id: "Palestine", name: "Palestine" },
    { id: "Panama", name: "Panama" },
    { id: "Papua New Guinea", name: "Papua New Guinea" },
    { id: "Paraguay", name: "Paraguay" },
    { id: "Peru", name: "Peru" },
    { id: "Philippines", name: "Philippines" },
    { id: "Poland", name: "Poland" },
    { id: "Portugal", name: "Portugal" },
    { id: "Puerto Rico", name: "Puerto Rico" },
    { id: "Qatar", name: "Qatar" },
    { id: "Romania", name: "Romania" },
    { id: "Russia", name: "Russia" },
    { id: "Rwanda", name: "Rwanda" },
    { id: "Samoa", name: "Samoa" },
    { id: "Saudi Arabia", name: "Saudi Arabia" },
    { id: "Senegal", name: "Senegal" },
    { id: "Serbia", name: "Serbia" },
    { id: "Seychelles", name: "Seychelles" },
    { id: "Sierra Leone", name: "Sierra Leone" },
    { id: "Singapore", name: "Singapore" },
    { id: "Sint Maarten", name: "Sint Maarten" },
    { id: "Slovenia", name: "Slovenia" },
    { id: "Solomon Islands", name: "Solomon Islands" },
    { id: "Somalia", name: "Somalia" },
    { id: "South Africa", name: "South Africa" },
    { id: "South Korea", name: "South Korea" },
    { id: "South Sudan", name: "South Sudan" },
    { id: "Spain", name: "Spain" },
    { id: "Sri Lanka", name: "Sri Lanka" },
    { id: "Suriname", name: "Suriname" },
    { id: "Sweden", name: "Sweden" },
    { id: "Switzerland", name: "Switzerland" },
    { id: "Taiwan", name: "Taiwan" },
    { id: "Tajikistan", name: "Tajikistan" },
    { id: "Tanzania", name: "Tanzania" },
    { id: "Thailand", name: "Thailand" },
    { id: "Türkiye", name: "Turkey" },
    { id: "Turkmenistan", name: "Turkmenistan" },
    { id: "Uganda", name: "Uganda" },
    { id: "Ukraine", name: "Ukraine" },
    { id: "United Arab Emirates", name: "United Arab Emirates" },
    { id: "United Kingdom", name: "United Kingdom" },
    { id: "United States", name: "United States" },
    { id: "Uruguay", name: "Uruguay" },
    { id: "Uzbekistan", name: "Uzbekistan" },
    { id: "Venezuela", name: "Venezuela" },
    { id: "Vietnam", name: "Vietnam" },
    { id: "Yemen", name: "Yemen" },
    { id: "Zambia", name: "Zambia" },
    { id: "Zimbabwe", name: "Zimbabwe" },
];

export const highlightUSStateList = [
    { id: 'alabama', name: 'Alabama' },
    { id: 'alaska', name: 'Alaska' },
    { id: 'arizona', name: 'Arizona' },
    { id: 'arkansas', name: 'Arkansas' },
    { id: 'california', name: 'California' },
    { id: 'colorado', name: 'Colorado' },
    { id: 'connecticut', name: 'Connecticut' },
    { id: 'delaware', name: 'Delaware' },
    { id: 'florida', name: 'Florida' },
    { id: 'georgia', name: 'Georgia' },
    { id: 'hawaii', name: 'Hawaii' },
    { id: 'idaho', name: 'Idaho' },
    { id: 'illinois', name: 'Illinois' },
    { id: 'indiana', name: 'Indiana' },
    { id: 'iowa', name: 'Iowa' },
    { id: 'kansas', name: 'Kansas' },
    { id: 'kentucky', name: 'Kentucky' },
    { id: 'louisiana', name: 'Louisiana' },
    { id: 'maine', name: 'Maine' },
    { id: 'maryland', name: 'Maryland' },
    { id: 'massachusetts', name: 'Massachusetts' },
    { id: 'michigan', name: 'Michigan' },
    { id: 'minnesota', name: 'Minnesota' },
    { id: 'mississippi', name: 'Mississippi' },
    { id: 'missouri', name: 'Missouri' },
    { id: 'montana', name: 'Montana' },
    { id: 'nebraska', name: 'Nebraska' },
    { id: 'nevada', name: 'Nevada' },
    { id: 'new hampshire', name: 'New Hampshire' },
    { id: 'new jersey', name: 'New Jersey' },
    { id: 'new mexico', name: 'New Mexico' },
    { id: 'new york', name: 'New York' },
    { id: 'north carolina', name: 'North Carolina' },
    { id: 'north dakota', name: 'North Dakota' },
    { id: 'ohio', name: 'Ohio' },
    { id: 'oklahoma', name: 'Oklahoma' },
    { id: 'oregon', name: 'Oregon' },
    { id: 'pennsylvania', name: 'Pennsylvania' },
    { id: 'rhode island', name: 'Rhode Island' },
    { id: 'south carolina', name: 'South Carolina' },
    { id: 'south dakota', name: 'South Dakota' },
    { id: 'tennessee', name: 'Tennessee' },
    { id: 'texas', name: 'Texas' },
    { id: 'utah', name: 'Utah' },
    { id: 'vermont', name: 'Vermont' },
    { id: 'virginia', name: 'Virginia' },
    { id: 'washington', name: 'Washington' },
    { id: 'west virginia', name: 'West Virginia' },
    { id: 'wisconsin', name: 'Wisconsin' },
    { id: 'wyoming', name: 'Wyoming' }
];